name: Security

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  trufflehog:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog
        uses: trufflesecurity/trufflehog@v3.30.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD

  audit:
    name: Cargo audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust env
        uses: ./.github/actions/setup-rust-env

      - name: Install Cargo Audit
        run: cargo install cargo-audit

      - name: Cargo Audit
        run: cargo audit
