name: Security

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "0 7 * * 1"

jobs:
  trufflehog:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: TruffleHog
        uses: trufflesecurity/trufflehog@v3.30.0
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
