name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust env
        uses: "./.github/actions/setup-rust-env"

      - name: Rust test
        run: cargo test

  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Rust env
        uses: "./.github/actions/setup-rust-env"

      - name: Rust check
        run: cargo check
